-- Language Goal OS MVP database schema
-- Run this in Supabase SQL Editor.
-- This MVP uses a device-level client_key, not full user accounts yet.

create table if not exists public.user_profiles (
  id uuid primary key default gen_random_uuid(),
  client_key text not null unique,
  interface_language text not null default 'ru',
  target_language text not null default 'en',
  goal text not null default 'new-country',
  level text not null default 'zero',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_attempts (
  id bigint generated by default as identity primary key,
  client_key text not null,
  goal text not null,
  level text not null,
  target_language text not null,
  scenario_id text not null,
  scenario_title text not null,
  answer text not null,
  score_total integer not null default 0,
  score_vocabulary integer not null default 0,
  score_position integer not null default 0,
  score_clarity integer not null default 0,
  help_opens integer not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists learning_attempts_client_key_created_at_idx
  on public.learning_attempts (client_key, created_at desc);

alter table public.user_profiles enable row level security;
alter table public.learning_attempts enable row level security;

drop policy if exists "mvp profiles select" on public.user_profiles;
drop policy if exists "mvp profiles insert" on public.user_profiles;
drop policy if exists "mvp profiles update" on public.user_profiles;
drop policy if exists "mvp attempts select" on public.learning_attempts;
drop policy if exists "mvp attempts insert" on public.learning_attempts;
drop policy if exists "mvp attempts delete" on public.learning_attempts;

-- MVP policies: allow browser beta users to save/read route and progress.
-- For a paid/public product, replace this with Supabase Auth + auth.uid()-based policies.
create policy "mvp profiles select"
  on public.user_profiles for select
  to anon, authenticated
  using (true);

create policy "mvp profiles insert"
  on public.user_profiles for insert
  to anon, authenticated
  with check (true);

create policy "mvp profiles update"
  on public.user_profiles for update
  to anon, authenticated
  using (true)
  with check (true);

create policy "mvp attempts select"
  on public.learning_attempts for select
  to anon, authenticated
  using (true);

create policy "mvp attempts insert"
  on public.learning_attempts for insert
  to anon, authenticated
  with check (true);

create policy "mvp attempts delete"
  on public.learning_attempts for delete
  to anon, authenticated
  using (true);
